# Generated by Django 6.0.3 on 2026-03-30 16:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('inicio', models.DateTimeField()),
                ('cierre', models.DateTimeField()),
                ('reparto_inicio', models.DateTimeField(blank=True, null=True)),
                ('reparto_fin', models.DateTimeField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='orders.ordercycle')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='accounts.cliente')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='accounts.tienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto_snapshot', models.CharField(max_length=150)),
                ('unidad_medida_snapshot', models.CharField(max_length=20)),
                ('precio_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.producto')),
                ('proveedor_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.proveedor')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='orders.pedido')),
            ],
            options={
                'ordering': ['nombre_producto_snapshot'],
            },
        ),
        migrations.AddConstraint(
            model_name='pedido',
            constraint=models.UniqueConstraint(fields=('ciclo', 'tienda'), name='unique_pedido_tienda_ciclo'),
        ),
        migrations.AlterUniqueTogether(
            name='lineapedido',
            unique_together={('pedido', 'producto')},
        ),
    ]
