# Generated by Django 5.2.7 on 2026-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_lineapedido_iva_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercycle',
            options={},
        ),
        migrations.RemoveField(
            model_name='ordercycle',
            name='reparto_fin',
        ),
        migrations.RemoveField(
            model_name='ordercycle',
            name='reparto_inicio',
        ),
        migrations.AddField(
            model_name='ordercycle',
            name='dias_reparto',
            field=models.CharField(blank=True, help_text='Ejemplo: Lunes y Martes', max_length=200),
        ),
        migrations.AlterField(
            model_name='ordercycle',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
