# Generated by Django 5.2.7 on 2026-05-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_ordercycle_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pedido',
            name='unique_pedido_tienda_ciclo',
        ),
    ]
